name: Frequent Language gist

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: inokawa/lang-box

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: sudo apt-get update
      - run: sudo apt-get install cmake pkg-config libicu-dev zlib1g-dev libcurl4-openssl-dev libssl-dev ruby-dev
      - run: sudo gem install github-linguist
      - run: npm install
      - run: npm start
        env:
          GH_TOKEN: ${{ secrets.GH_Secret }}
          GIST_ID: 7fac1206fabcd38633bb3c4963450199
          USERNAME: ${{ github.actor }}