name: Work Time Gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "* * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_Secret }}
          GIST_ID: 30888696e271e94b5720256edf8408e7
          TIMEZONE: Europe/Brussels